version: '3.9'

services:
  ecommerce-app:
    build: .
    container_name: ecommerce-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:./data/ecommerce-db
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./data:/app/data
    restart: unless-stopped
